<Project>
  <PropertyGroup>
    <LangVersion>10</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="netstandard">
      <HintPath>$(ValheimGamePath)\valheim_Data\Managed\netstandard.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
  <Import Project="$(MSBuildThisFileDirectory)lib\HarmonyValidator.targets" />
</Project>
